# Fly.io configuration for SNRT Search API
app = "snrt-search"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  # Environment variables will be set via fly secrets

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.ports]]
  port = 80
  handlers = ["http"]

[[http_service.ports]]
  port = 443
  handlers = ["tls", "http"]

[http_service.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20

[[http_service.checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "5s"
  method = "get"
  path = "/"
  protocol = "http"
  tls_skip_verify = false 